
CREATE TABLE dbo.PanelAIEvaluation (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PanelId INT NULL,
    AIEvaluationStatus varchar(15) NULL,
	AIEvaluationStatusComment nvarchar(max),
    Strengths NVARCHAR(MAX) NULL,
    AreasForImprovement NVARCHAR(MAX) NULL,
    OverallEvaluation NVARCHAR(MAX) NULL,
    FinalRatingInNumber FLOAT NULL,
    FinalRatingInText NVARCHAR(255) NULL,
	FileName NVARCHAR(500),
	FileContent NVARCHAR(max),
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    ModifiedDate DATETIME NULL,
    PanelName NVARCHAR(500) NULL,
    PanelEmail NVARCHAR(500) NULL,
    RecruiterName NVARCHAR(500) NULL,
    RecruiterEmail NVARCHAR(500) NULL,
    InterviewDate NVARCHAR(200),
    InterviewName NVARCHAR(500) NULL,
    Interviewer NVARCHAR(500) NULL,
    MainStream NVARCHAR(500) NULL,
    StreamsCovered NVARCHAR(500) NULL,
    TotalQuestionsAsked int NULL,
    TargetExperienceTier NVARCHAR(500) NULL,
    CandidateExperienceYears  NVARCHAR(100) NULL,
    QuestionsAskedByPanel NVARCHAR(max) NULL,
    MaxRatingValue NVARCHAR(100) NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
	[CreatedBy] INT NOT NULL, 
	[CreatedOn] DATETIME2(0) NOT NULL, 
	[UpdatedBy] INT NULL, 
	[UpdatedOn] DATETIME2(0) NULL,
)
