CREATE TABLE [dbo].[Position]
(
	[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[PositionId] [decimal](18, 0) UNIQUE NOT NULL ,
	[SrNumber] [decimal](18, 0) NULL,
	[Client] [nvarchar](255) NULL,
	[ProjectName] [nvarchar](255) NULL,
	[BusinessUnit] [nvarchar](100) NULL,
	[Region] [nvarchar](100) NULL,
	[PositionStudio] [nvarchar](100) NULL,
	[PositionTitle] [nvarchar](255) NULL,
	[srPosition] [nvarchar](255) NULL,
	[Seniority] [nvarchar](100) NULL,
	[TypeOfPosition] [nvarchar](100) NULL,
	[AIPodRole] [nvarchar](100) NULL,
	[IndustrySpecialization] [nvarchar](255) NULL,
	[ContractorAllowed] [bit] NULL,
	[WorkOffice] [nvarchar](100) NULL,
	[SecondaryLocation] [nvarchar](255) NULL,
	[PositionFramework] [nvarchar](100) NULL,
	[ClientInterviewRequired] [bit] NULL,
	[EnglishRequired] [bit] NULL,
	[PositionLoad] [decimal](5, 2) NULL,
	[StartDate] [datetime] NULL,
	[GloberToBeAssigned] [nvarchar](255) NULL,
	[Stage] [nvarchar](100) NULL,
	[Replacement] [bit] NULL,
	[Handler] [nvarchar](255) NULL,
	[AssociateHandler] [nvarchar](255) NULL,
	[HandlerTeam] [nvarchar](100) NULL,
	[AssociateHandlerTeam] [nvarchar](100) NULL,
	[RateAmount] [nvarchar](20) NULL,
	[RatePeriod] [nvarchar](50) NULL,
	[Submitter] [nvarchar](255) NULL,
	[SubmitDate] [datetime] NULL,
	[Aging] [int] NULL,
	[EstimatedStaffingDate] [datetime] NULL,
	[LastSyncedUtc] [datetime2](7) NULL DEFAULT getutcdate(),
	[IsActive] [bit] NULL DEFAULT ((1)), 
    CONSTRAINT [PK_Position] PRIMARY KEY ([Id])
)
GO
CREATE NONCLUSTERED INDEX [UX_Position_PositionId] ON [dbo].[Position](PositionId)
GO