<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Configurations>Debug;Release;Development;QA;Production</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.24" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="MySql.Data" Version="8.4.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.20.0" />
		<PackageReference Include="Azure.Identity" Version="1.11.4" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.18.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
		<PackageReference Include="Google.Apis.Drive.v3" Version="1.57.0.2746" />
		<PackageReference Include="Google.Apis.PeopleService.v1" Version="1.57.0.2707" />
		<PackageReference Include="Google.Apis.Sheets.v4" Version="1.57.0.2727" />
		<PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
		<PackageReference Include="System.Text.Json" Version="9.0.5" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Academy.Core\Academy.Core.csproj" />
	  <ProjectReference Include="..\Academy.Domain\Academy.Domain.csproj" />
	</ItemGroup>

</Project>
