# =======================================================
# Academy.FE (Angular SSR)
# =======================================================

FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install -f

COPY . .

ARG APP_ENV=development
ARG GOOGLE_CLIENT_ID=""

# Inject Google Client ID
RUN sed -i "s|GoogleProviderClientId: \"\"|GoogleProviderClientId: \"${GOOGLE_CLIENT_ID}\"|g" src/environments/environment*.ts

# Build
RUN if [ "$APP_ENV" = "prod" ]; then \
      npm run build; \
    else \
      npm run build -- --configuration=$APP_ENV; \
    fi

# ─────────────────────────────

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

RUN npm install -f --omit=dev

CMD ["node","dist/academy/server/server.mjs"]